// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $blog_layout from "./routes/blog/_layout.tsx";
import * as $chronicle from "./routes/chronicle.tsx";
import * as $grace from "./routes/grace.tsx";
import * as $greet_firstName_lastName_ from "./routes/greet/[firstName]/[lastName].tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $kindred from "./routes/kindred.tsx";
import * as $light from "./routes/light.tsx";
import * as $nexustx from "./routes/nexustx.tsx";
import * as $openws from "./routes/openws.tsx";
import * as $profile_name_ from "./routes/profile/[[name]].tsx";
import * as $roots from "./routes/roots.tsx";
import * as $scroll from "./routes/scroll.tsx";
import * as $tale from "./routes/tale.tsx";
import * as $test_dynamic from "./routes/test-dynamic.tsx";
import * as $test from "./routes/test.tsx";
import * as $user_name_ from "./routes/user/[name].tsx";
import * as $wallex from "./routes/wallex.tsx";
import * as $within from "./routes/within.tsx";
import * as $BannerScroll from "./islands/BannerScroll.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DinamicTextContainer from "./islands/DinamicTextContainer.tsx";
import * as $DynamicHeader from "./islands/DynamicHeader.tsx";
import * as $DynamicParagraph from "./islands/DynamicParagraph.tsx";
import * as $DynamicSubtitle from "./islands/DynamicSubtitle.tsx";
import * as $DynamicTagline from "./islands/DynamicTagline.tsx";
import * as $DynamicTextContainer from "./islands/DynamicTextContainer.tsx";
import * as $DynamicTitle from "./islands/DynamicTitle.tsx";
import * as $PosterBanner from "./islands/PosterBanner.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/blog/_layout.tsx": $blog_layout,
    "./routes/chronicle.tsx": $chronicle,
    "./routes/grace.tsx": $grace,
    "./routes/greet/[firstName]/[lastName].tsx": $greet_firstName_lastName_,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/kindred.tsx": $kindred,
    "./routes/light.tsx": $light,
    "./routes/nexustx.tsx": $nexustx,
    "./routes/openws.tsx": $openws,
    "./routes/profile/[[name]].tsx": $profile_name_,
    "./routes/roots.tsx": $roots,
    "./routes/scroll.tsx": $scroll,
    "./routes/tale.tsx": $tale,
    "./routes/test-dynamic.tsx": $test_dynamic,
    "./routes/test.tsx": $test,
    "./routes/user/[name].tsx": $user_name_,
    "./routes/wallex.tsx": $wallex,
    "./routes/within.tsx": $within,
  },
  islands: {
    "./islands/BannerScroll.tsx": $BannerScroll,
    "./islands/Counter.tsx": $Counter,
    "./islands/DinamicTextContainer.tsx": $DinamicTextContainer,
    "./islands/DynamicHeader.tsx": $DynamicHeader,
    "./islands/DynamicParagraph.tsx": $DynamicParagraph,
    "./islands/DynamicSubtitle.tsx": $DynamicSubtitle,
    "./islands/DynamicTagline.tsx": $DynamicTagline,
    "./islands/DynamicTextContainer.tsx": $DynamicTextContainer,
    "./islands/DynamicTitle.tsx": $DynamicTitle,
    "./islands/PosterBanner.tsx": $PosterBanner,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
